global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"

    scrape_interval: 15s
    scrape_timeout: 15s

    static_configs:
      - targets: ["localhost:9091"]
  - job_name: "mahakala"

    scrape_interval: 15s
    scrape_timeout: 15s

    static_configs:
      - targets: ["host.docker.internal:4201"]
